# Default initial positions for devol's ros2_control fake system

apollo_elbow_joint: 0
apollo_robotiq_85_left_knuckle_joint: 0
apollo_shoulder_lift_joint: 0
apollo_shoulder_pan_joint: 0
apollo_wrist_1_joint: 0
apollo_wrist_2_joint: 0
apollo_wrist_3_joint: 0
artemis_elbow_joint: 0
artemis_robotiq_85_left_knuckle_joint: 0
artemis_shoulder_lift_joint: 0
artemis_shoulder_pan_joint: 0
artemis_wrist_1_joint: 0
artemis_wrist_2_joint: 0
artemis_wrist_3_joint: 0
