# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    use_sim_time: true

    apollo_hand_controller:
      type: parallel_gripper_action_controller/GripperActionController


    apollo_ur_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    artemis_hand_controller:
      type: parallel_gripper_action_controller/GripperActionController

    artemis_ur_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    apollo_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    artemis_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

artemis_hand_controller:
  ros__parameters:
    use_sim_time: true
    joint: artemis_robotiq_85_left_knuckle_joint
artemis_ur_manipulator_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - artemis_shoulder_pan_joint
      - artemis_shoulder_lift_joint
      - artemis_elbow_joint
      - artemis_wrist_1_joint
      - artemis_wrist_2_joint
      - artemis_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

apollo_hand_controller:
  ros__parameters:
    use_sim_time: true
    joint: apollo_robotiq_85_left_knuckle_joint
apollo_ur_manipulator_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - apollo_shoulder_pan_joint
      - apollo_shoulder_lift_joint
      - apollo_elbow_joint
      - apollo_wrist_1_joint
      - apollo_wrist_2_joint
      - apollo_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
