<?xml version="1.0"?>

<!-- Reference: https://github.com/lucasmazzetto/gazebo_differential_drive_robot -->
<robot name="diff_drive" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- Import diff macro -->
    <xacro:include filename="$(find diff_drive_description)/urdf/diff_drive_macro.urdf.xacro"/>
    <!-- ros2_control description -->
    <xacro:include filename="$(find diff_drive_description)/urdf/diff_drive.ros2_control.xacro"/>

    <!-- Robot Parameters -->
    <xacro:arg name="parent" default="empty"/>  <!-- Set this to world for rviz and others -->
    <xacro:arg name="body_length" default="0.5"/>
    <xacro:arg name="body_width" default="0.3"/>
    <xacro:arg name="body_height" default="0.1"/>
    <xacro:arg name="body_density" default="7850.0"/>
    <xacro:arg name="wheel_radius" default="0.1"/>
    <xacro:arg name="wheel_width" default="0.05"/>
    <xacro:arg name="wheel_density" default="900"/>
    <xacro:arg name="caster_radius" default="0.1"/>
    <xacro:arg name="caster_density" default="0.1"/>
    <xacro:arg name="max_linear_acceleration" default="10"/>
    <xacro:arg name="use_gazebo" default="true"/>
    <xacro:arg name="tf_prefix" default=""/>

    <xacro:property name="body_width" value="$(arg body_width)"/>
    <xacro:property name="wheel_width" value="$(arg wheel_width)"/>
    <xacro:property name="wheel_separation" value="${(body_width) + (wheel_width)}"/>

    <link name="$(arg parent)"/>
    <xacro:diff_drive 
        tf_prefix="$(arg tf_prefix)"
        parent="$(arg parent)"
        body_length="$(arg body_length)"
        body_width="$(arg body_width)"
        body_height="$(arg body_height)"
        body_density="$(arg body_density)"
        wheel_radius="$(arg wheel_radius)"
        wheel_width="$(arg wheel_width)"
        wheel_density="$(arg wheel_density)"
        caster_radius="$(arg caster_radius)"
        caster_density="$(arg caster_density)"
        max_linear_acceleration="$(arg max_linear_acceleration)"
    />

    <xacro:if value="$(arg use_gazebo)">
        <xacro:include filename="$(find diff_drive_description)/urdf/diff_drive.gazebo.xacro"/>
        <xacro:diff_drive_gazebo 
            wheel_separation="${(wheel_separation)}"
            wheel_radius="$(arg wheel_radius)"
            max_linear_acceleration="$(arg max_linear_acceleration)" 
            tf_prefix="$(arg tf_prefix)"/>
    </xacro:if>

    <xacro:diff_drive_ros2_control name="diff_drive_ros2_control" tf_prefix="$(arg tf_prefix)" use_gazebo="$(arg use_gazebo)"/>
</robot>