<?xml version="1.0"?>

<!-- Reference: https://github.com/lucasmazzetto/gazebo_differential_drive_robot -->
<robot xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- import macros -->
    <xacro:include filename="$(find diff_drive_description)/urdf/diff_drive_macro.urdf.xacro"/>
    <xacro:include filename="$(find devol_description)/urdf/devol_macro.urdf.xacro"/>

    <xacro:macro name="devol_drive" params="
        parent
        name
        tf_prefix
        ur_type
        joint_limit_params
        kinematics_params
        physical_params
        visual_params
        transmission_hw_interface
        safety_limits
        safety_pos_margin
        safety_k_position
        use_mock_hardware
        mock_sensor_commands
        robot_ip
        script_filename
        input_recipe_filename
        output_recipe_filename
        initial_positions
        *origin
        use_gazebo
        force_abs_paths
        body_length:=0.5
        body_width:=0.3
        body_height:=0.1
        body_density:=7850.0
        wheel_radius:=0.1
        wheel_width:=0.05
        wheel_density:=900
        caster_radius:=0.1
        caster_density:=0.1
        max_linear_acceleration:=10
    ">
        <xacro:property name="caster_offset" value="${body_length/2 - caster_radius}"/>

        <xacro:diff_drive 
            parent="${parent}"
            tf_prefix="${tf_prefix}"
            body_length="${body_length}"
            body_width="${body_width}"
            body_height="${body_height}"
            body_density="${body_density}"
            wheel_radius="${wheel_radius}"
            wheel_width="${wheel_width}"
            wheel_density="${wheel_density}"
            caster_radius="${caster_radius}"
            caster_density="${caster_density}"
            max_linear_acceleration="${max_linear_acceleration}"
        />

        <xacro:devol 
            parent="${tf_prefix}body_link" 
            name="${name}"
            tf_prefix="${tf_prefix}" 
            ur_type="${ur_type}"
            joint_limit_params="${joint_limit_params}"
            kinematics_params="${kinematics_params}"
            physical_params="${physical_params}"
            visual_params="${visual_params}"
            transmission_hw_interface="${transmission_hw_interface}"
            safety_limits="${safety_limits}"
            safety_pos_margin="${safety_pos_margin}"
            safety_k_position="${safety_k_position}"
            use_mock_hardware="${use_mock_hardware}"
            mock_sensor_commands="${mock_sensor_commands}"
            robot_ip="${robot_ip}"
            script_filename="${script_filename}"
            input_recipe_filename="${input_recipe_filename}"
            output_recipe_filename="${output_recipe_filename}"
            initial_positions="${xacro.load_yaml((initial_positions_file))}"
            use_gazebo="${use_gazebo}"
            force_abs_paths="${force_abs_paths}"
            >
            <origin xyz="0 0 ${caster_offset}" rpy="0 0 0"/>
        </xacro:devol>
    </xacro:macro>

</robot>
